### ISSUE TITLE
Can't share or make lists

### ISSUE THREAD

**Issue by iMakeThing** [Snail-IDE/snail-ide.github.io#10]
### Expected Behavior

I should be able to share / make lists.

### Actual Behavior

I get error Unknown error. The file may be too large or something unexpected happened. Full error: FormatError2 when using a valid .snail file and there's no list button...

### Steps to Reproduce

Go to the website, share

### Operating System and Browser

Windows 10, Google Chrome 119

**Comment by iMakeThing** [comment]
![image](https://github.com/Snail-IDE/snail-ide.github.io/assets/150251545/aff8f440-d4a8-4b65-80c3-07e7a14c3d03)

**Comment by dumorando** [comment]
visit this link [https://backend.nmsderp.repl.co/](https://backend.nmsderp.repl.co/) to hopefully wake the server up, if it doesnt work, try again later.
