### ISSUE TITLE
All of my projects ( .snail ) don't import and say 0MB

### ISSUE THREAD

**Issue by xendyex** [Snail-IDE/snail-ide.github.io#13]
### Expected Behavior
They should let me share!

### Actual Behavior

Error:
```
Unknown error. The file may be too large or something unexpected happened. Full error: FormatError2
```
even if I start the server

### Steps to Reproduce

Upload my file ( http://xendy.co.uk/stuffs/snailOnlineTest.snail ) to Snail ( using upload button won't import so go to the page and then upload file )

### Operating System and Browser
Ubuntu 23.04 Firefox 120

**Comment by dumorando** [comment]
try multiple times and if it doesnt work try again later
