### ISSUE TITLE
Update Extensions

### ISSUE THREAD

**Issue by SharkPool-SP** [Snail-IDE/snail-ide.github.io#20]
Variables Expanded is why out of date. Use the current version, it doesn't crash and is much better.

Also, it would be best if you just fetched the files directly from my repository so you don't have to manually update it every time it's changed

**Comment by nmsderp** [comment]
We fetch for most of your extensions, seems I forgot to change that one, thanks for telling me

**Comment by nmsderp** [comment]
I'll have to do it later though

**Comment by nmsderp** [comment]
Done!
