### ISSUE TITLE
Blocks in the palette area get jumbled up after changing addons.

### ISSUE THREAD

**Issue by MightyTheArmiddilo** [Snail-IDE/snail-ide.github.io#22]
### Expected Behavior

What normally happens.

### Actual Behavior

Blocks in the palette area get jumbled up
![Screenshot 2024-02-13 10 43 53 PM](https://github.com/Snail-IDE/snail-ide.github.io/assets/132609476/5ffb16d8-142e-4194-b38b-7eaa2be2e8ae)

### Steps to Reproduce

Use this file in the addons page:
[turbowarp-addon-settings (2).json](https://github.com/Snail-IDE/snail-ide.github.io/files/14276106/turbowarp-addon-settings.2.json)

### Operating System and Browser

Google ChromeOS Version 121.0.6167.159 (Official Build) (64-bit)

**Comment by nmsderp** [comment]
Did you make this .json file in another scratch mod or scratch addons

**Comment by MightyTheArmiddilo** [comment]
> Did you make this .json file in another scratch mod or scratch addons

I originally tried the one I had from Penguin Mod, it had the same result, so I tried manually adding the addons in after resetting the settings, did that mess it up?

**Comment by nmsderp** [comment]
Most likely

**Comment by nmsderp** [comment]
closed due to no response
