### ISSUE TITLE
Cant upload projects, gets stuck on importing

### ISSUE THREAD

**Issue by Rubiidev-18** [Snail-IDE/snail-ide.github.io#24]
### Expected Behavior

No importing screen, straight to where I can upload the project.

### Actual Behavior

Infinite importing screen

### Steps to Reproduce

1. Press the upload button. that it

### Operating System and Browser

Chrome On Android 14, Samsung One UI 6

**Comment by nmsderp** [comment]
We are fixing server stuff right now, so you will have to wait
