### ISSUE TITLE
Open source the project backend.

### ISSUE THREAD

**Issue by someCatInTheWorld** [Snail-IDE/snail-ide.github.io#27]
If it's closed source because of API keys, couldn't you just put the API keys in an environment variable or in a file that's .gitignored?

**Comment by nmsderp** [comment]
It is open source just we don't update the repo anymore, we scrapped the php server and hosted the old one on somewhere else

**Comment by dumorando** [comment]
yea its in NewServer. the only thing we forgot to change in the repo was the new domain, but you can do that in success.html
