### ISSUE TITLE
I don’t know what repository this should be in

### ISSUE THREAD

**Issue by RalseiGithub** [Snail-IDE/snail-ide.github.io#34]
I’m pretty sure the “load from desktop” option should be able to load the .snail files

It instead asks for a .pm file. The same with penguin mod instead of a .pmp file (I’m on iPad btw).

It just won’t allow for a .snail file to be picked.

I use safari on iPad (not jailbreaked).

**Comment by RalseiGithub** [comment]
Just go to the (online) editor and click the “add to desktop” option and it will only allow .pm files (is this an apple or iPad thing?)

**Comment by nmsderp** [comment]
i don't use IOS maybe another dev does, so i can't help here, just use the website for now

**Comment by thepython555** [comment]
it allows pm, pmp, AND snail files.

**Comment by RalseiGithub** [comment]
No when I go to select a pmp, sb3 or snail file on snail or penguin mod it won’t let me select them to use at all there greyed out only .pm files work.

**Comment by thepython555** [comment]
huh, weird. well none of the devteam has a iphone/ipad/whatever apple product so we can't really fix this until it becomes replicable on our phones or a pc.

**Comment by nmsderp** [comment]
closing this #37 kinda goes with this
