### ISSUE TITLE
Unix Timestamp Reporter Block Bug

### ISSUE THREAD

**Issue by SilvanZwick** [Snail-IDE/snail-ide.github.io#39]
### Expected Behavior

The unix timestamp reporter block will output the unix timestamp, like it's supposedly supposed to do.

### Actual Behavior

A warning icon (<img width="44" alt="image" src="https://github.com/Snail-IDE/snail-ide.github.io/assets/119003429/ebe18cf9-f2d1-4bd8-9a98-085512924215">) appears in the toolbar, and when you press it, this appears:
<img width="358" alt="image" src="https://github.com/Snail-IDE/snail-ide.github.io/assets/119003429/327a1840-256e-4277-adfc-93ae9f42b99a">
### Steps to Reproduce

Click on the Unix Timestamp reporter block in the Editor\>Sensing tab\><img width="119" alt="image" src="https://github.com/Snail-IDE/snail-ide.github.io/assets/119003429/40fe2150-b260-4a42-bf3c-caf9c807b136"> or use the Unix Timestamp reporter block (Editor\>Sensing tab\><img width="119" alt="image" src="https://github.com/Snail-IDE/snail-ide.github.io/assets/119003429/40fe2150-b260-4a42-bf3c-caf9c807b136">) in code. Examples:

https://github.com/Snail-IDE/snail-ide.github.io/assets/119003429/5716c4f6-11b0-49f9-b45d-e9edf695d8e4

https://github.com/Snail-IDE/snail-ide.github.io/assets/119003429/adadbf81-3e3e-46ba-9b8a-adaf225a05c1

### Operating System and Browser

macOS Sonoma 14.0, Google Chrome 123.0.6312.87 (Official Build) (arm64), MacBook Pro 14" 2021 with Apple M1 Pro

**Comment by SilvanZwick** [comment]
#### Note: When you use it in code (e.x. setting a variable to its value), nothing in the code will run. Not if you put it in the code while it's in a loop (I was putting it in an all at one in a forever loop), or when you put it in and then click it.

**Comment by nmsderp** [comment]
we are aware, we are probably going to temporary hide these blocks

**Comment by nmsderp** [comment]
they have been temporary hiden

**Comment by nmsderp** [comment]
never mind hiding them broke the editor

**Comment by dumorando** [comment]
this is because we didnt properly add it to the vm yet. the warnings can be ignored for now, but you cant use them in packaged projects.

**Comment by SilvanZwick** [comment]
I happen to be very curious, so... here's a question:
Why does the block give warnings and why can't you run code with that block in it?

**Comment by dumorando** [comment]
> I happen to be very curious, so... here's a question: Why does the block give warnings and why can't you run code with that block in it?

the reason it gives warnings is because we didn't feed the vm the code it actually needs to run. blocks with said reporter in it will fail (i think) because the vm doesnt have the code that it can execute the block with. it works by itself, because the function is there, but there is no compiled code. i dont know if that makes sense lol

**Comment by nmsderp** [comment]
this has been fixed
