### ISSUE TITLE
project title on project page doesn't replace emojis

### ISSUE THREAD

**Issue by raynepaws** [Snail-IDE/snail-ide.github.io#48]
### Expected Behavior

should show emojis like everywhere else on website

### Actual Behavior

`:chip:` displays
![Screenshot from 2024-05-26 17-38-04](https://github.com/Snail-IDE/snail-ide.github.io/assets/129226914/0e326daa-feb6-45d5-8217-67ef3615ac21)

### Steps to Reproduce

- go to a project
- look at top of screen

### Operating System and Browser

firefox on linux mint cinnamon

**Comment by nmsderp** [comment]
its not supposed to

**Comment by raynepaws** [comment]
> its not supposed to

![sorry](https://github.com/Snail-IDE/snail-ide.github.io/assets/129226914/57cc68d9-940f-491c-afd6-f22f0248d382)
