### ISSUE TITLE
lists problem

### ISSUE THREAD

**Issue by Randomuser12342** [Snail-IDE/snail-ide.github.io#49]
### Expected Behavior

should wait, and work

### Actual Behavior

does not wait and causes glitches in my project

### Steps to Reproduce

uhh...

### Operating System and Browser

Windows 10 22H2 Microsoft Edge Version 125.0.2535.92 (Official build) (64-bit)

**Comment by someCatInTheWorld** [comment]
What block is it?

**Comment by Randomuser12342** [comment]
> What block is it?

set [] to array ()

**Comment by nmsderp** [comment]
closed due to inactivity
