### ISSUE TITLE
I have no clue what the bug is here

### ISSUE THREAD

**Issue by Sooparch** [Snail-IDE/snail-ide.github.io#50]
### Expected Behavior

the game should run perfectly

### Actual Behavior

the game runs perfectly

### Steps to Reproduce

use the randomutils extention

### Operating System and Browser

windows 11 - edge

![Screenshot 2024-06-15 000758](https://github.com/Snail-IDE/snail-ide.github.io/assets/69817759/d71507f7-67af-4a9b-8412-548ec70670e3)

**Comment by nmsderp** [comment]
can you send the .snail file?

**Comment by nmsderp** [comment]
closed to inactivity
