### ISSUE TITLE
this.props.vm.runtime.renderer is undefined (LibreWolf)

### ISSUE THREAD

**Issue by LunTheProto** [Snail-IDE/snail-ide.github.io#59]
### Expected Behavior

Load editor

### Actual Behavior

![2024-10-25 22_51_07-Snail IDE - A mod of PenguinMod — LibreWolf](https://github.com/user-attachments/assets/12b6d9b4-d24c-4d3d-b08c-f403aafa59fa)

### Steps to Reproduce

Go to https://editor.snail-ide.com/editor.html

### Operating System and Browser

Windows 11 x64, LibreWolf

**Comment by someCatInTheWorld** [comment]
[Try enabling WebGL, LibreWolf disables it by default.](https://github.com/Snail-IDE/snail-ide.github.io/issues/59) (You may want to use an extension like CanvasBlocker to preserve your privacy, and whitelist us in it because we need WebGL for applying sprite effects.)

**Comment by LunTheProto** [comment]
Thanks, That worked. I forgot its disabled by default.
