### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SharkPool-SP** [Snail-IDE/snail-ide.github.io#6]
Why are my extensions here?

**Comment by nmsderp** [comment]
I really enjoy your extensions so I added some of them. If you would like them removed please just tell me.

**Comment by SharkPool-SP** [comment]
> I really enjoy your extensions so I added some of them. If you would like them removed please just tell me.

No no it's fine. Just next time let me know. 

+Some of them are outdated. You should really be pulling the data from my gallery files so it's always up to date
