### ISSUE TITLE
Open documentation button doesn't work.

### ISSUE THREAD

**Issue by redspacecat** [Snail-IDE/snail-ide.github.io#65]
When an extension is loaded and there is an "Open Documentation" button, it doesn't do anything when clicked, and doesn't appear to throw any errors in the console.

**Comment by nmsderp** [comment]
Dupe https://github.com/Snail-IDE/snail-ide.github.io/issues/46

**Comment by redspacecat** [comment]
I do not know how I couldn't have seen that.
